sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - libssl-dev
    - wamerican
script:
   - make test
   - make test CC=gcc CXX=g++
