sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libssl-dev
    - wamerican
    - pv
    - valgrind
script:
   - make test
   - make test CC=clang
